version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.AmazonProductAdvertising.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: iffNN4PoqaJDALd5fx/kv3B26jR7qmrhFjmxxZpVjLqQHY7woNt4qMaJfgqijPYc
  artifact: /.*\.nupkg/