version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.AmazonProductAdvertising.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: 1Kl9f9ZjK4TwiWWMhyCO6TLriKceRziKjD34CzD/Hgt9GiWCnN/jFx7NgLhzA/pg
  artifact: /.*\.nupkg/
