version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.AmazonProductAdvertising.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: F1bfh7s77JOk08FN41Tb1ANHW1fQSwSC26iVMhBSRwoIyZnR+cEQ6K6bB3lx9SLH
  artifact: /.*\.nupkg/
